CREATE TABLE MEMBER (
    USER_ID VARCHAR(20) PRIMARY KEY,
    USER_PWD VARCHAR(256) NOT NULL,
    USER_NM VARCHAR(20) NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
	HEIGHT NUMBER(3) , 
	WEIGHT NUMBER(3) , 
	PRIVATE_YN VARCHAR(1) DEFAULT ('N'), 	-- 개인정보 보호여부 
	REGDATE TIMESTAMP 
) ;


